# Generated by Django 4.1.7 on 2023-03-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_create_tables_and_table_entries_tables'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tableentry',
            name='line_column_unique',
        ),
        migrations.AddConstraint(
            model_name='tableentry',
            constraint=models.UniqueConstraint(models.F('line'), models.F('column'), models.F('table_id'), name='line_column_unique'),
        ),
    ]
